dev:
	cargo build --release
	# ./target/release/aquarium ODoyLDY3Miw3MjE=
	# ./target/release/aquarium Njo4LDAyNiw2NTE=
	# ./target/release/aquarium NTo1LDUzNCwzODM=
	./target/release/aquarium Mzo2LDU3MSw2MjM=
